services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  weather-bot:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres_data: 